language: ruby

rvm:
  - '2.2.4'

services: postgresql

before_script:
  # Update phantomjs. Built-in version doesnt support Function.prototype,bind
  - mkdir travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH

  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake db:test:prepare

script: bundle exec rspec
